# Generated by Django 5.2.4 on 2025-07-16 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='skin_images/%Y/%m/%d/')),
                ('predicted_disease', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('image_size', models.CharField(blank=True, max_length=50)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skin Analysis',
                'verbose_name_plural': 'Skin Analyses',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
